### PR TITLE
Add stagingWorkspaceId attribute to sandbox (PS-800)

### PR DESCRIPTION
**Pull request by JakubMatejka**

### CODE REVIEW

**Comment by JakubMatejka** [comment]
Shoot! The tests are still connected to the serverless testing and I probably can't connect it easily to the AZ testing in VPN. 😕 What would you say if I send it to review without passing CI as it is a higher prio thing? 😬 Luckily it's a small and understandable code change so not that big harm.(?) 🙈

**Comment by JakubMatejka** [comment]
Thanks. 😄 (Just to be clear, I don't expect you to sit here for me whole weekend, ok? I'm just compensating my free time in the morning so it's quite ok if you go enjoy your weekend and return on Monday. 😄 🍻 )

**Comment by pivnicek** [comment]
hahaha, no worries :-).  I'm just heading out now.  But I will be working also on sunday (I've many tasks remaining:)

**Comment by JakubMatejka** [comment]
Yeah, I'll be probably also stopping by in the evening tomorrow or Sunday. ;o) 

BTW. I would release this as new major version to separate it from that serverless api completely.

**Pull request merged**
