### PR TITLE
PS-3126 Identify sandbox types which uses Python

### PR DESCRIPTION
**Pull request by joker806**
https://keboola.atlassian.net/browse/PS-3126
Needed for: https://github.com/keboola/sandboxes/pull/294

### CODE REVIEW

**Comment by joker806** [comment]
Sorry, wrong PR, this is not ready for review yet.

**Comment by joker806** [comment]
Ready now

**Review by pivnicek — APPROVED** [review]
ok, but this makes me want to do the kernels :-)

**Comment by joker806** [comment]
I have a simpler solution - let's just move these arya constants (type arrays) from Sandboxes API PHP client to sandboxes :) The API client really doesn't need to know abything about it, it's sandboxes component stuff :)

I just already spent more than enough time on this initiaitive and had to leave something as is :smile:

**Pull request merged**
